project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Home"
        href: Home.qmd
      - text: "SQ2: Temperature & Precipitation"
        href: sq2.qmd
      - text: "SQ5: Time of Day & Day of Week"
        href: https://karenn-dotcom.github.io/STA9750-2025-FALL/ind_rep.html
      - text: "SQ6: E-Bike vs. Classic"
        href: https://sabrinazhuu.github.io/STA9750-2025-FALL/individual_report.html
        
  #page-footer:
    #right:
    #  - icon: github
    #    href: https://github.com/christopherryotan/STA9750-2025-FALL
    #  - icon: linkedin
    #    href: https://www.linkedin.com/in/christopher-tan-8a9538236/

format:
  html:
    theme: default
    css: styles.css
    toc: true
    smooth-scroll: true
